#pragma once

#define MAP 999
#define GRID 9999
#define BOARD	99999

#define SCENE_SECTION_UNKNOWN -1
#define SCENE_SECTION_TEXTURES 2
#define SCENE_SECTION_SPRITES 3
#define SCENE_SECTION_ANIMATIONS 4
#define SCENE_SECTION_ANIMATION_SETS	5
#define SCENE_SECTION_OBJECTS	6

#define OBJECT_TYPE_MARIO	0
#define OBJECT_TYPE_BRICK	1
#define OBJECT_TYPE_GOOMBA	2
#define OBJECT_TYPE_KOOPAS	3
#define OBJECT_TYPE_PIRANHAPLANT 10

#define OBJECT_TYPE_JUST_FOR_SHOW 8

#define OBJECT_TYPE_INVISIBLE	11
#define OBJECT_TYPE_PIPE_HITBOX 12
#define OBJECT_TYPE_PIPE_FOR_SHOW 13
#define OBJECT_TYPE_COLOR_BRICK_HITBOX 14

#define OBJECT_TYPE_QBRICK	15

#define OBJECT_TYPE_COIN	16

#define OBJECT_TYPE_MUSHROOM	17

#define OBJECT_TYPE_GROUND	18

#define OBJECT_TYPE_LEAF	19

#define OBJECT_TYPE_PORTAL	50

#define OBJECT_TYPE_WOOD	51

#define OBJECT_TYPE_FLOATING_COIN	52

#define OBJECT_TYPE_RED_KOOPAS		53

#define OBJECT_TYPE_BROKEN_BRICK	54

#define OBJECT_TYPE_QUESTION_BROKEN_BRICK	55

#define OBJECT_TYPE_NOTE_BRICK		56

#define OBJECT_TYPE_ENDGAME_BRICK	57

#define OBJECT_TYPE_CHOSEN_ITEM		58

#define OBJECT_TYPE_BOOMERANG_GUY	59

#define OBJECT_TYPE_BOOMERANG		60

#define OBJECT_TYPE_PIRANHA_FLOWER	61

#define OBJECT_TYPE_MUSHROOM_CARD	1000
#define OBJECT_TYPE_FLOWER_CARD		1001
#define OBJECT_TYPE_STAR_CARD		1002

#define OBJECT_TYPE_GAMEOVER_MENU	9999
#define OBJECT_TYPE_COURSE_BOARD	9990
#define OBJECT_TYPE_PORTAL_PIPE		9991
#define OBJECT_TYPE_PORTAL_PIPE_IMAGE	9992
#define OBJECT_TYPE_GREEN_MUSHROOM		62
#define OBJECT_TYPE_BRICK_WITH_PSWITCH	9994
#define OBJECT_TYPE_MUSIC_TO_HEAVEN_BRICK	9995

#define MAX_SCENE_LINE 1024
